services:
  db: 
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: guestbook
      POSTGRES_USER: guestbook
      POSTGRES_DB: guestbook
    volumes:
      - db-data:/var/lib/postresql
    ports: 
      - 5433:5432
  redis:
    image: valkey/valkey
    ports: 
      - 6380:6379
volumes:
  db-data: